"""add shift date range fields

Revision ID: add_shift_date_range_fields
Revises: 6ea14ce19836
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_shift_date_range_fields'
down_revision: Union[str, Sequence[str], None] = '6ea14ce19836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_report', sa.Column('shift_start_date', sa.Date(), nullable=True))
    op.add_column('shift_report', sa.Column('shift_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_report', 'shift_end_date')
    op.drop_column('shift_report', 'shift_start_date')
    # ### end Alembic commands ### 