"""update salary settings to profit based

Revision ID: 8f5d9e2f3b34
Revises: 7f4c8d9e1a23
Create Date: 2024-07-11 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5d9e2f3b34'
down_revision = '7f4c8d9e1a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем новые колонки для прибыли
    op.add_column('salary_settings', sa.Column('min_daily_profit', sa.Float(), nullable=False, server_default='100.0'))
    op.add_column('salary_settings', sa.Column('bonus_profit_threshold', sa.Float(), nullable=False, server_default='150.0'))
    
    # Удаляем старые колонки для количества заявок
    op.drop_column('salary_settings', 'min_requests_per_day')
    op.drop_column('salary_settings', 'bonus_requests_threshold')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Восстанавливаем старые колонки для количества заявок
    op.add_column('salary_settings', sa.Column('min_requests_per_day', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('salary_settings', sa.Column('bonus_requests_threshold', sa.Integer(), nullable=False, server_default='70'))
    
    # Удаляем новые колонки для прибыли
    op.drop_column('salary_settings', 'min_daily_profit')
    op.drop_column('salary_settings', 'bonus_profit_threshold')
    
    # ### end Alembic commands ### 